
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_gems_bootcamp_development

test:
  <<: *default
  database: ruby_gems_bootcamp_test


production:
  <<: *default
  database: ruby_gems_bootcamp_production
  username: ruby_gems_bootcamp
  password: <%= ENV['RUBY_GEMS_BOOTCAMP_DATABASE_PASSWORD'] %>
